[project]
name = "p2p-client"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Arsalan", email = "arsalanhussain547@gmail.com" }]
requires-python = ">=3.12"
dependencies = ["libp2p>=0.7.0"]

[project.scripts]
p2p-client = "p2p_client:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
